feat: Convert all issue templates into issue forms
EddieHubCommunity/api pull request #164
Opened 2021-07-22 21:48 UTC by Panquesito7

Things added/changed:

- Convert all issue templates into issue forms.
- Disable blank issues, but provide an `Other` generic template for all kinds of issues.
  - The `Other` template is taken from some of @nhcarrigan's projects. Thanks, Nick! 😄

2021-07-22 22:40 UTC, nhcarrigan requested changes
Need the correct labels here.

2021-07-22 22:40 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/bug.yml
> +labels: ["💣 Bug"]
```suggestion
labels: ["🛠 goal: fix"]
```

2021-07-22 22:40 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/feature.yml
> +labels: ["⭐ goal addition"]
```suggestion
labels: ["⭐ goal: addition"]
```

2021-07-22 22:40 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/other.yml
> +labels: [triage]
```suggestion
labels: ["🚦 status: awaiting triage"]
```

2021-07-26 14:00 UTC, nhcarrigan approved these changes
Looks good to me

2021-07-31 09:20 UTC, eddiejaoude approved these changes
Great team work 💪

2021-07-31 09:21 UTC, merged